name: minspo-todos-security
services:
  db:
    image: postgres:15
    container_name: minspo-todos-security-postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minspo-todos-security
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on