spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/minspo-todos-security
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update